apiVersion: v1
kind: Secret
metadata:
  name: hello-secret
type: Opaque
data:
  username: YWRtaW4=   # "admin" encodé en base64
  password: MWYyZDFlMmU2N2Rm  # "1f2d1e2e67df" encodé en base64
  color: IzIwMA==