apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-daemonset
spec:
  replicas: 3
  strategy: 
    type: Recreate 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.takima.io/school/proxy/nginx:1.9.1
        ports:
        - containerPort: 80
